### PR TITLE
Update Feature Section

### PR DESCRIPTION
**Pull request by beedemo-dev**

### CODE REVIEW

**Comment by beedemo-dev** [comment]
Preview environment for context `generated` is accessible at: https://env-n-1d1130a.previews.workshop.cb-sa.io/.


<details>
<summary>Details</summary>
<p>

* The environment name is _env-n-1d1130a_.
* The environment was created for the Git commit _b6ed07201a782ce2dc436acc9a67e90bb6db4174_.
* The environment will be accessible until this pull request is closed.
* You can update the environment by pushing changes to this pull request.
  Depending on the _auto-update_ setting for this context, the environment will update automatically or you need to explicitly request a new preview by adding a another `/preview comment`.

</p>
</details>

**Comment by beedemo-dev** [comment]
Preview environment for context `default` is accessible at: https://env-n-b84cf8c.previews.workshop.cb-sa.io/.


<details>
<summary>Details</summary>
<p>

* The environment name is _env-n-b84cf8c_.
* The environment was created for the Git commit _b6ed07201a782ce2dc436acc9a67e90bb6db4174_.
* The environment will be accessible until this pull request is closed.
* You can update the environment by pushing changes to this pull request.
  Depending on the _auto-update_ setting for this context, the environment will update automatically or you need to explicitly request a new preview by adding a another `/preview comment`.

</p>
</details>

**Comment by galonsomartinez** [comment]
back to blue

**Comment by beedemo-dev** [comment]
Preview environment for context `default` is accessible at: https://env-n-b84cf8c.previews.workshop.cb-sa.io/.


<details>
<summary>Details</summary>
<p>

* The environment name is _env-n-b84cf8c_.
* The environment was created for the Git commit _f804d18cb1f051588cc0ba50593d9d996bbe292d_.
* The environment will be accessible until this pull request is closed.
* You can update the environment by pushing changes to this pull request.
  Depending on the _auto-update_ setting for this context, the environment will update automatically or you need to explicitly request a new preview by adding a another `/preview comment`.

</p>
</details>

**Comment by galonsomartinez** [comment]
back to blue

**Pull request merged**
